export const userStyles = {
  p15: { padding: "15px" },
  imageStyles: { borderRadius: "10px", objectFit: "cover" },
  attendeesVideo: {
    border: "5px solid black",
    margin: "10px",

    borderRadius: "10px",
    height: "89px",
    width: "100%",
  },
  usersImages: { borderRadius: "10px", objectFit: "cover" },
  usersParent: {
    backgroundColor: "black",
    maxHeight: "100vh",
    padding: "2%",
    justifyContent: "space-evenly",
    overflowY: "auto",
    overflowX: "hidden",
  },
  mb20: { marginBottom: "20px" },
  flexStart: {
    display: "flex",
    flexDirection: "column",
    alignSelf: "flex-end",
    alignItems: "flex-start",
  },
  brandName: { color: "#fff", fontSize: "16px", fontWeight: "bold" },
  cityName: { color: "#fff", fontSize: "16px" },
  followBtn: {
    borderRadius: "10px",
    width: "92px",
    height: "22px",
    textAlign: "center",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  emojiContainer: {
    backgroundColor: "#3B3C40",
    borderRadius: "50px",
    height: "50px",
    width: "50px",
    margin: "5px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  mainScreen: { display: "flex" },
  mainScreenVideo: {
    borderRadius: "50px",
    objectFit: "cover",
  },
  mainScreenTopRow: {
    color: "#fff",
    position: "absolute",
    zIndex: "2",
    paddingInline: "20px",
    padding: "30px",
    width: "-webkit-fill-available",
    display: "flex",
    justifyContent: "space-between",
  },
  mainScreenLiveContainer: {
    background: "#fff",
    display: "flex",
    justifyContent: "space-evenly",
    width: "242px",
    alignItems: "center",
    // padding: "10px",
    // height: "46px",
    borderRadius: "15px",
  },
  mainScreenLiveDot: {
    borderRadius: "50px",
    background: "#DD4B4E",
    width: "30px",
    height: "30px",
  },
  mainScreenLiveText: { fontSize: "22px", fontWeight: "600", color: "#000000" },
  mainScreenLiveTime: { fontSize: "22px", color: "#000000" },
  mainScreenIconContainer: {
    display: "flex",
    justifyContent: "space-evenly",
    width: "100px",
  },
  settingsIcon: { fontSize: "28px" },
  expandIcon: {
    fontSize: "28px",
    background: "transparent",
    border: "none",
    cursor: "pointer",
  },
  bottomRow: {
    alignSelf: "flex-end",
    color: "#fff",
    position: "absolute",
    zIndex: "2",
    paddingInline: "20px",
    padding: "30px",
    width: "-webkit-fill-available",
    display: "flex",
    justifyContent: "flex-end",
  },
  viewerCount: { fontSize: "18px", fontWeight: "600", color: "#fff" },
};
