export const bottomStyles = {
  iconContainer: {
    backgroundColor: "#3B3C40",
    borderRadius: "50px",
    height: "50px",
    width: "50px",
    margin: "2px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  indexRow: { height: "150px", overflowX: "hidden", paddingInline: "20px" },
  rightIcons: {
    backgroundColor: "#3B3C40",
    borderRadius: "50px",
    height: "50px",
    width: "50px",
    margin: "2px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  followContainer: {
    display: "flex",
    justifyContent: "space-evenly",
  },
  flexColumn: {
    display: "flex",
    flexDirection: "column",
  },
  brandName: { color: "#fff", fontSize: "16px", fontWeight: "bold" },
  brandCity: { color: "#fff", fontSize: "16px" },
  followBtn: {
    borderRadius: "10px",
    width: "92px",
    height: "22px",
    textAlign: "center",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
};
