export const Modal_Styles = {
  redcolor: {
    color: "red",
  },
  textStyling: {
    fontFamily: "Lato",
    fontStyle: "normal",
    fontWeight: "normal",
    fontSize: "18px",
    color: "#FFFFFF",
  },
  textAreaStyle: {
    resize: "none",
    borderRadius: "10px",
    background: "#3B3C40",
    borderRadius: "10px",
    border: "0px",
  },
  respondBoxes: {
    background: "#3B3C40",
    border: "1px solid #7DE6D0",
    boxSizing: "border-box",
    width: "23%",
    // height: 70,
    borderRadius: "10px",
    paddingLeft: "10px",
    paddingTop: "10px",
  },
  respondBoxesText: {
    fontFamily: "Lato",
    fontstyle: "normal",
    fontHeight: "300",
    fontSize: "10px",
    lineHeight: "17px",
    /* identical to box height */
    alignSelf: "start",
    color: "#FFFFFF",
  },
  respondBoxNumbering: {
    paddingLeft: "10px",
    color: "#FFFF",
  },
  respondBoxCircle: {
    height: "44px",
    width: "90%",
    borderRadius: "10px",
    border: "1px solid #FFFFFF",
  },
  options: {
    background: "#3B3C40",
    borderRadius: "10px",
    border: "none",
    marginTop: "20px",
  },
  addOptions: {
    background: "#3B3C40",
    borderRadius: "10px",
    width: "100%",
    border: "none",
    marginTop: "10px",
    display: "flex",
    // justifyContent: "center",
    alignItems: "center",
  },
  addOptionsText: { color: "white", alignSelf: "flex-start" },
  postBtn: {
    alignSelf: "center",
    justifySelf: "center",
    width: "50%",
    marginTop: "10px",
    background: "#74ACEC",
    borderRadius: "10px",
    color: "#fff",
    border: "none",
  },
  previousQuestion: {
    fontFamily: "Poppins",
    fontStyle: "normal",
    fontWeight: "600",
    fontSize: "18px",
    lineHeight: "27px",
    /* identical to box height */
    marginTop: "20px",
    color: "#FFFFFF",
  },
  panelHeight: {
    height: 200,
    overflowY: "auto",
  },
  timeStamp: {
    fontFamily: "Lato",
    fontStyle: "normal",
    fontWeight: "300",
    fontSize: "10px",
    lineHeight: "12px",
    /* identical to box height */

    color: "#FFFFFF",
  },
  attendeesSummery: {
    fontFamily: "Lato",
    fontStyle: "normal",
    fontWeight: "300",
    fontSize: "14px",
    lineHeight: "17px",
    color: "#FFFFFF",
  },
  questionOptionsText: {
    fontFamily: "Lato",
    fontStyle: "normal",
    fontWeight: "300",
    fontSize: "14px",
    lineHeight: "17px",
    color: "#FFFFFF",
  },
  optionHolder: {
    display: "flex",
    justifyContent: "space-between",
  },
};
