export const Component_Styles = {
  dimensionParent: {
    width: "100%",
    background: "#4E5054",
    borderRadius: "15px",
  },
  dimensionHeading: {
    fontFamily: "Lato",
    fontStyle: "normal",
    fontHeight: " 300",
    fontSize: "24px",
    lineHeight: "29px",
    /* identical to box height */
    marginTop: "10px",
    marginBottom: "12px",
    color: "#FFFFFF",
  },
  dimensionContainerRow: {
    width: "147px",
    height: "107px",
    padding: "10px",
    border: "3px solid transparent",
    borderRadius: "10px",
    display: "flex",
    flexDirection: "column",
    background: "#3B3C40",
    marginTop: "5px",
    alignItems: "center",
    justifyContent: "center",
  },
  dimensionContainerColumn: {
    width: "147px",
    height: "107px",
    padding: "10px",
    border: "3px solid transparent",
    borderRadius: "10px",
    display: "flex",
    alignItems: "center",
    marginRight: "10px",
    marginTop: "5px",
    background: "#3B3C40",
    alignItems: "center",
    justifyContent: "center",
  },
  layout1: {
    border: "2px solid #fff",
    borderRadius: "10px",

    width: "113px",
    height: "83px",
  },
  layout2: {
    border: "2px solid #fff",
    borderRadius: "10px",

    width: "90px",
    height: "83px",
  },
  layout3: {
    border: "2px solid #fff",
    borderRadius: "10px",
    width: "75px",
    height: "66px",
  },
  layout4_1: {
    border: "2px solid #fff",
    borderRadius: "10px",
    width: "91px",
    height: "67px",
  },
  layout4: {
    border: "2px solid #fff",
    borderRadius: "10px",
    width: "29px",
    height: "26px",
  },
  layout5: {
    border: "2px solid #fff",
    borderRadius: "10px",
    width: "39px",
    height: "83px",
  },
  layout6_1: {
    border: "2px solid #fff",
    borderRadius: "10px",
    width: "66px",
    height: "83px",
  },
  layout6: {
    border: "2px solid #fff",
    borderRadius: "10px",
    width: "46px",
    height: "42px",
  },
  layout7: {
    border: "2px solid #fff",
    borderRadius: "10px",
    width: "56px",
    height: "46px",
  },
  layout8: {
    border: "2px solid #fff",
    borderRadius: "10px",
    width: "38px",
    height: "40px",
  },
  layout9_1: {
    border: "2px solid #fff",
    borderRadius: "8px",
    width: "91px",
    height: "67px",
  },
  layout9: {
    border: "2px solid #fff",
    borderRadius: "8px",
    width: "22px",
    height: "25px",
  },
  flexColumn: {
    display: "flex",
    flexDirection: "column",
  },
  wrapFlex: {
    display: "flex",
    flexWrap: "wrap",
  },
  flexContent: {
    display: "flex",
    justifyContent: "center",
  },
};
