export const componentStyles = {
  graphContainer: {
    width: "354px",
    height: "16vh",
    background: "#3B3C40",
    borderRadius: "15px",
    marginBottom: "20px",
    display: "flex",
    flexDirection: "column",
    paddingTop: "10px",
    paddingBottom: "5px",
  },
  graphHeadings: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    paddingInline: "30px",
  },
  lightWhiteColor: {
    color: "#E5E5E5",
  },
  secondColumnContainer: {
    // height: "",
    display: "flex",
    flexDirection: "column",
    // justifyContent: "space-evenly",
    alignItems: "center",
  },
  activityFeedsContainer: {
    width: "393px",
    height: "100%",
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-start",
    alignItems: "center",
    background: "#4E5054",
    borderRadius: " 15px",
    paddingTop: "20px",
    marginBottom: "10px",
  },
  actionComponentContainer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: "10px",
    marginLeft: "10px",
    width: "100%",
  },
  wd100: {
    width: "100%",
  },
  colorWhite: {
    color: "white",
  },
  activityFeedPanel: {
    // backgroundColor: "#4E5054",
    border: "none",
    display: "flex",
    flexDirection: "column",
    padding: 0,
  },
  adminChatContainer: {
    width: "393px",
    marginTop: "10px",
  },
  fontBold: {
    fontWeight: "bold",
  },
  adminChatHeading: {
    fontWeight: "bold",
    fontSize: "20px",
    alignSelf: "center",
    color: "#fff",
  },
  flexColumn: {
    display: "flex",
    flexDirection: "column",
  },
  headerContainer: {
    display: "flex",
    borderRadius: "20px",
    width: "100%",
    height: "7%",
    background: "#4E5054",
    justifyContent: "space-evenly",
    paddingInline: "20px",
    alignItems: "center",
    marginBottom: "15px",
  },
  liveButton: {
    width: "76px",
    height: "33px",
    left: "40px",
    top: "32px",
    background: "#DD4B4E",
    borderRadius: "5px",
    textAlign: "center",
    paddingTop: "5px",
  },
  headerText: {
    color: "#fff",
    alignSelf: "centers",
  },
  headerComponentText: {
    fontFamily: "Lato",
    fontStyle: "normal",
    fontWeight: "300",
    fontSize: "18px",
    lineHeight: "22px",
    /* identical to box height */

    color: "#FFFFFF",
  },
  popoverContentContainer: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-evenly",
    width: "100%",
  },
  popoverHeader: {
    display: "flex",
    justifyContent: "space-between",
    width: "100%",
  },
  closeIcon: {
    width: "25px",
    height: "25px",
  },
  attendeesContainer: {
    width: "100%",
    height: "82vh",

    overflowY: "auto",
  },
  searchIcon: {
    marginRight: "10px",
    color: "#fff",
    fontWeight: "bold",
    fontSize: "18px",
  },
  searchInput: {
    width: "200px",
    borderRadius: "8px",
    marginBottom: "20px",
    marginLeft: "5%",
  },
  listItemContainer: {
    display: "flex",
    justifyContent: "space-between",
    borderBottom: "1px solid #4E5054",
  },
  mr10: {
    marginRight: "10px",
  },
  infoIcon: {
    color: "#fff",
    fontSize: "18px",
  },
  sendChatIcon: {
    all: "unset ",
    cursor: "pointer",
  },
  sendIconHolder: {
    transform: "rotate(310deg)",
    fontSize: "20px",
    color: "#fff",
  },
  emojiIcon: {
    fontSize: "20px",
    color: "#fff",
    marginRight: "10px",
  },
  mainChatContainer: {
    width: "100%",
    border: "none",
    height: "80vh",
    display: "flex",
    flexDirection: "column",
    paddingInline: "10px",
    overflow: "auto",
  },
  messageArrayList: {
    overflow: "auto",
    flex: "1",
  },
  messageRow: {
    display: "flex",
    alignItems: "flex-start",
  },
  messageContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
  },
  senderName: {
    color: "#fff",
    fontFamily: "Lato",
    fontStyle: "normal",
    fontWeight: "300",
    fontSize: "8px",
    lineHeight: "10px",
  },
  sendMessageContainer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  mainChatMessageInput: {
    borderRadius: "50px",
    border: "none",
    padding: "10px",
    paddingInline: "15px",
  },
  tabsHolder: {
    width: "100%",
    height: "100%",
  },
  tabPaneHolder: {
    height: "100%",
    width: "460px",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    backgroundColor: "#4E5054",
    borderBottom: "none",
    borderRadius: "20px",
    paddingInline: "15px",
  },
  h100: {
    height: "100%",
  },
  activityFeedListContainer: {
    marginBottom: "10px",
    width: "100%",
    height: "37vh",
    overflowY: "auto",
    backgroundColor: "#3B3C40",
  },
  listItem: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    borderBottom: "1px solid #4E5054",
  },
  listFeedData: {
    color: "#fff",
    justifySelf: "center",
    alignSelf: "flex-start",
    fontSize: "14px",
  },
  messageTime: {
    color: "#fff",
    alignSelf: "flex-end",
    fontSize: "9px",
  },
  swiperContainer: {
    height: "50%",
    width: "100%",
    borderRadius: "50%",
    marginBottom: "10px",
  },
  actionComponentText: {
    fontFamily: "Lato",
    fontStyle: "normal",
    fontWeight: "normal",
    fontSize: "18px",
    lineHeight: "22px",
    alignSelf: "flex-start",
    color: "#ffffff",
  },
  quickActionTextHolder: {
    display: "flex",
    justifyContent: "flex-end",
    width: "44%",
    height: "120px",
  },
};
