export const componentStyles = {
  graphContainer: {
    width: "90%",
    height: "20%",
    background: "#3B3C40",
    borderRadius: "15px",
    marginBottom: "20px",
    display: "flex",
    flexDirection: "column",
    paddingTop: "10px",
    paddingBottom: "5px",
  },
  graphHeadings: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    paddingInline: "30px",
  },
  lightWhiteColor: {
    color: "#E5E5E5",
  },
  secondColumnContainer: {
    // height: "",
    display: "flex",
    flexDirection: "column",
    padding: "10px",
    // justifyContent: "space-evenly",
    alignItems: "center",
    // height: "-webkit-fill-available",
  },
  activityFeedsContainer: {
    width: "100%",
    // height: "80%",
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-start",
    alignItems: "center",
    background: "#4E5054",
    borderRadius: " 15px",
    paddingTop: "20px",
    // marginBottom: "10px",
  },
  actionComponentContainer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    // marginBottom: "10px",
    // marginLeft: "10px",
    width: "100%",
    padding: "10px",
  },
  wd100: {
    width: "100%",
  },
  colorWhite: {
    color: "white",
  },
  attendeesListingText: {
    fontFamily: "Lato",
    fontStyle: "normal",
    fontWeight: "300 !important",
    fontSize: "18px",
    color: "#fff",
  },
  quickActionText: {
    fontFamily: "Poppins",
    fontStyle: "normal",
    fontWeight: "600",
    fontSize: "24px",
    lineHeight: "36px",
    color: "white",
    fontSize: "24px",
  },
  activityFeedPanel: {
    // backgroundColor: "#4E5054",
    border: "none",
    display: "flex",
    flexDirection: "column",
    padding: 0,
  },
  adminChatContainer: {
    // width: "393px",
    marginTop: "10px",
    width: "100%",
  },
  fontBold: {
    fontWeight: "bold",
  },
  adminChatHeading: {
    fontWeight: "bold",
    fontSize: "20px",
    alignSelf: "center",
    color: "#fff",
  },
  flexColumn: {
    display: "flex",
    flexDirection: "column",
  },
  headerContainer: {
    padding: "5px",
    borderRadius: "20px",
    background: "#4E5054",
    marginBottom: "15px",
    display: "flex",
    justifyContent: "space-evenly",
    flexWrap: "nowrap",
    alignItems: "center",
  },
  headerParentContainer: {
    // padding: "8px",
    marginTop: "5px",
    marginBottom: "5px",
    width: "100%",
    // height: "33px",
    // margin: "10px",
    background: "#3B3C40",
    borderRadius: "15px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    whiteSpace: "nowrap",
  },
  headerParentContainer1: {
    padding: "10px",
    // width: "fit-content",
    // height: "33px",
    margin: "10px",
    background: "#3B3C40",
    borderRadius: "15px",
    // display: "flex",
    // justifyContent: "center",
    // alignItems: "center",
  },
  liveButton: {
    // padding: "5px",
    height: "25px",
    background: "#DD4B4E",
    borderRadius: "5px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    textAlign: "center",
    marginLeft: "5px",
    // width: "100px",
  },
  headerText: {
    color: "#fff",
    alignSelf: "baseline",
  },
  headerComponentText: {
    fontFamily: "Lato",
    fontStyle: "normal",
    fontWeight: "300",
    fontSize: "10px",
    lineHeight: "22px",
    /* identical to box height */
    color: "#FFFFFF",
    marginLeft: "10px",
  },
  popoverContentContainer: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-evenly",
    width: "100%",
  },
  popoverHeader: {
    display: "flex",
    justifyContent: "space-between",
    width: "100%",
  },
  closeIcon: {
    width: "25px",
    height: "25px",
  },
  attendeesContainer: {
    // width: "100%",
    height: "100vh",
    padding: "0px 5px",
    overflowY: "auto",
  },
  searchIcon: {
    marginRight: "10px",
    color: "#fff",
    fontWeight: "bold",
    fontSize: "18px",
  },
  searchInput: {
    width: "200px",
    borderRadius: "8px",
    marginBottom: "20px",
    marginLeft: "5%",
  },
  listItemContainer: {
    display: "flex",
    justifyContent: "space-between",
    borderBottom: "1px solid #4E5054",
  },
  mr10: {
    marginRight: "10px",
  },
  infoIcon: {
    color: "#fff",
    fontSize: "18px",
  },
  sendChatIcon: {
    all: "unset ",
    cursor: "pointer",
  },
  sendIconHolder: {
    transform: "rotate(310deg)",
    fontSize: "20px",
    color: "#fff",
  },
  emojiIcon: {
    fontSize: "20px",
    color: "#fff",
    marginRight: "10px",
  },
  mainChatContainer: {
    width: "100%",
    border: "none",
    height: "100vh ",
    display: "flex",
    flexDirection: "column",
    paddingInline: "10px",
    overflow: "auto",
  },
  messageArrayList: {
    overflow: "auto",
    flex: "1",
  },
  messageRow: {
    display: "flex",
    alignItems: "flex-start",
  },
  messageRowRevert: {
    display: "flex",
    alignItems: "flex-start",
    flexDirection: "row-reverse",
  },
  messageContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
  },
  senderName: {
    color: "#fff",
    fontFamily: "Lato",
    fontStyle: "normal",
    fontWeight: "300",
    fontSize: "8px",
    lineHeight: "10px",
  },
  receiverName: {
    color: "#fff",
    fontFamily: "Lato",
    fontStyle: "normal",
    fontWeight: "300",
    fontSize: "8px",
    lineHeight: "10px",
    alignSelf: "flex-end",
  },
  sendMessageContainer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  mainChatMessageInput: {
    borderRadius: "50px",
    border: "none",
    padding: "10px",
    paddingInline: "15px",
  },
  tabsHolder: {
    width: "100%",
    // height: "-webkit-fill-available",
  },
  tabPaneHolder: {
    // height: "100%",
    // width: "460px",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    backgroundColor: "#4E5054",
    borderBottom: "none",
    borderRadius: "20px",
    paddingInline: "15px",
  },
  h100: {
    height: "100%",
  },
  activityFeedListContainer: {
    marginBottom: "10px",
    // width: "100%",
    maxHeight: "31vh",
    overflowY: "scroll",
    backgroundColor: "#3B3C40",
  },
  listItem: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    borderBottom: "1px solid #4E5054",
  },
  listFeedData: {
    color: "#fff",
    justifySelf: "center",
    alignSelf: "flex-start",
    fontSize: "14px",
  },
  messageTime: {
    color: "#fff",
    alignSelf: "flex-end",
    fontSize: "9px",
  },
  swiperContainer: {
    // height: "50%",
    // width: "100%",
    borderRadius: "50%",
    marginBottom: "10px",
  },
  actionComponentText: {
    fontFamily: "Lato",
    fontStyle: "normal",
    fontWeight: "normal",
    fontSize: "18px",
    lineHeight: "22px",
    alignSelf: "flex-start",
    color: "#ffffff",
    // width: 70%;
  },
  askTheAudienceText: {
    fontFamily: "Lato",
    fontStyle: "normal",
    fontWeight: "normal",
    // height: "6rem",
    width: "100%",
    fontSize: "18px",
    lineHeight: "22px",
    alignSelf: "flex-start",
    color: "#ffffff",
  },
  quickActionTextHolder: {
    display: "flex",
    justifyContent: "flex-end",
    flexDirection: "column",
    cursor: "pointer",
    width: "100%",
    height: "6rem",
    // height: 100px;
    padding: "5px 10px",
    alignSelf: "center",
    justifySelf: "center",
    marginRight: "10px",
    // margin-bottom: 10px;
    // display: flex;
    // flex-direction: column;
    // justify-content: space-between;
    // padding: 5px 10px;
    background: "#74acec",
    borderRadius: "15px",
  },
  videoSlider: {
    width: "170px !important",
    borderRadius: "15px !important",
  },
  imageHolder: {
    height: "6rem",
    width: "100%",
    marginTop: "5px",
    marginBottom: "10px",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    padding: "5px 10px",
    backgroundImage:
      "url('https://influence.digital/wp-content/uploads/2021/09/giphy-4-1.gif')",
    borderRadius: "15px",
  },
  sendMessageIcon: {
    transform: "rotate(310deg)",
    fontSize: "20px",
    color: "#fff",
  },
  smileIcon: { fontSize: "20px", color: "#fff", marginRight: "10px" },
  adminChatInnerContainer: {
    // width: "100%",
    // height: "45vh",
    maxHeight: "39vh",
    border: "none",
    display: "flex",
    justifyContent: "space-between",
    flexDirection: "column",
    paddingInline: "10px",
    // overflow: "auto",
    backgroundColor: "#4E5054",
    borderBottom: "none",
    borderRadius: "20px",
    padding: "10px",
    paddingInline: "20px",
  },
  adminChatHeadingInner: {
    fontFamily: "Poppins",
    fontStyle: "normal",
    fontWeight: "600",
    fontSize: "24px",
    lineHeight: "36px",
    marginBottom: "30px",
    color: "#FFFFFF",
  },
  adminChatList: {
    overflowX: "auto",
    height: "50vh",
    height: "100%",
    marginBottom: "10px",
  },
  messageArray: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
  },
  messageText: {
    fontFamily: "Lato",
    fontStyle: "normal",
    fontWeight: "normal",
    fontSize: "14px",
  },
  m10: {
    marginRight: "10px",
    marginLeft: "10px",
  },
  swiperImageContainer: {
    "--swiper-navigation-color": "#fff",
    "--swiper-pagination-color": "#fff",
    width: "100%",
    height: "20rem",
  },
  audienceEngagementHeading: {
    fontFamily: "Poppins ",
    fontStyle: "normal ",
    fontWeight: "600 ",
    fontSize: "24px ",
    lineHeight: "36px ",
    color: "#fff",
    width: "90%",
  },
  quickActionWrapper: {
    background: "#4e5054",
    borderRadius: "15px",
    padding: "10px",
    paddingInlineStart: "20px",
  },
  quickActionContainer: {
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "flex-start",
  },
  modalButtonDesign: {
    width: "194px ",
    height: " 32px ",
    borderRadius: "10px ",
    marginBottom: "10px ",
    background: "#dd4b4e ",
  },
};
