export const fullScreenStyles = {
  f18: { fontSize: "28px" },
  flexStretch: {
    display: "flex",
    justifyContent: "stretch",
  },
  mainVideo: {
    objectFit: "cover",
    width: "100vw",
    height: "85vh",
  },
  videoOverlay: {
    color: "#fff",
    position: "absolute",
    zIndex: "2",
    paddingInline: "20px",
    padding: "30px",
    width: "-webkit-fill-available",
    display: "flex",
    justifyContent: "space-between",
  },
  liveContainer: {
    background: "#fff",
    display: "flex",
    justifyContent: "space-evenly",
    width: "242px",
    alignItems: "center",
    height: "46px",
    borderRadius: "15px",
  },
  liveRedDot: {
    borderRadius: "50px",
    background: "#DD4B4E",
    width: "30px",
    height: "30px",
  },
  liveText: { fontSize: "22px", fontWeight: "600", color: "#000000" },
  liveTime: { fontSize: "22px", color: "#000000" },
  iconContainer: {
    display: "flex",
    justifyContent: "space-evenly",
    width: "100px",
  },
  expandIcon: {
    fontSize: "28px",
    background: "transparent",
    border: "none",
    cursor: "pointer",
  },
  viewerCountDiv: {
    alignSelf: "flex-end",
    color: "#fff",
    position: "absolute",
    zIndex: "2",
    paddingInline: "20px",
    padding: "30px",
    width: "-webkit-fill-available",
    display: "flex",
    justifyContent: "flex-end",
  },
  viewerCount: { fontSize: "18px", fontWeight: "600", color: "#fff" },
  ////////////////
  indexContainer: {
    display: "flex",
    flexDirection: "column",
    background: "#000",
    overflowX: "hidden",
  },
};
